witmotion_imu:
    port: ttyUSB0
    baud_rate: 921600  # HWT906默认波特率
    polling_interval: 5 # 高波特率需要更短间隔
    timeout_ms: 50
    restart_service_name: /restart_imu
    imu_publisher:
        topic_name: /imu
        frame_id: imu
        use_native_orientation: true
        measurements:
            acceleration:
                enabled: true
                covariance: [ 0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01 ]
            angular_velocity:
                enabled: true
                covariance: [ 0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01 ]
            orientation:
                enabled: true
                covariance: [ 0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01 ]
    temperature_publisher:
        enabled: true
        topic_name: /temperature
        frame_id: imu
        from_message: acceleration
        variance: 0.01
        coefficient: 1.0
        addition: 0.0
    magnetometer_publisher:
        enabled: true
        topic_name: /magnetometer
        frame_id: imu
        coefficient: 1.0
        addition: 0.0
        covariance: [ 0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01 ]
    orientation_publisher:
        enabled: true
        topic_name: /orientation
    rtc_publisher:
        enabled: false